INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2009, 500000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2010, 500000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2011, 500000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2012, 500000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2013, 550000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2014, 550000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2015, 1000000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2016, 550000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2017, 550000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2018, 550000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2019, 600000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2020, 600000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2021, 600000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2022, 600000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2023, 650000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2024, 700000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2025, 700000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
INSERT INTO "AnnualLimit" ("year", "limitCents") VALUES (2026, 700000)
ON CONFLICT("year") DO UPDATE SET "limitCents" = excluded."limitCents";
