// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";

import "dotenv/config";
import { defineConfig } from "prisma/config";

const defaultDatabaseUrl = `file:${path.resolve("prisma/dev.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? defaultDatabaseUrl,
  },
});
